### ISSUE TITLE
Warning: Undefined variable $move_item_status_ok

### ISSUE THREAD

**Issue by judecooks** [jradwan/Piwigo-physical_photo_move#31]
Getting an error with moving a new (blank) album in Piwigo 13.7 and PPM 2.10.  I am trying to move a new album, nested inside of an album, into a different, new blank top-level album.  Both albums created physically via SFTP, database resynchronized, and then attempting to do a physical move via the the plugin.  I get this error:

Warning: Undefined variable $move_item_status_ok in ....../plugins/physical_photo_move/include/functions.inc.php on line 632
Warning: Undefined variable $move_item_status_ok in ....../plugins/physical_photo_move/include/functions.inc.php on line 646

Cannot modify header information - headers already sent by (output started at ....../plugins/physical_photo_move/include/functions.inc.php:632) in .../include/page_header.php on line 99

Piwigo: 13.7.0
Installed on 10 March 2019, 4 years 2 months 3 weeks 1 day ago
Operating system: Linux
PHP: 8.0.28
MySQL: 8.0.28-0ubuntu0.20.04.3
Graphics Library: External ImageMagick 6.9.7-4

**Comment by jradwan** [comment]
Replicated:

- created two empty physical folders in two separate locations

![image](https://github.com/jradwan/Piwigo-physical_photo_move/assets/11047158/a448f43f-98f0-477a-8309-89dd8b7d162c)

- attempt to move empty album to another, error occurs:

![image](https://github.com/jradwan/Piwigo-physical_photo_move/assets/11047158/fa4f524e-2d26-4b95-b377-63dcbb171abc)

The fact that the target album is empty really doesn't matter here. The problem is the code in the ppm_move_file_or_folder function isn't expecting the source folder to be empty. I think the main code block that would iterate through all the items is skipped, so the $move_item_status_ok variable is never set. So when the code gets to the end and tries to check that variable, the error occurs.

Should be an easy fix, just need to check if the directory is empty.

**Comment by jradwan** [comment]
@judecooks  Could you please try the updated https://github.com/jradwan/Piwigo-physical_photo_move/blob/2.21/include/functions.inc.php on your Piwigo installation and confirm it fixes the issue for you? Seems to be working fine here with my own testing.

**Comment by judecooks** [comment]
Thanks so much jradwan!  Love your extension - and physical albums!  :-)
