### ISSUE TITLE
something went wrong

### ISSUE THREAD

**Issue by chhoki** [jradwan/Piwigo-physical_photo_move#7]
Hi Jeremy,
I've installed your plugin to move picture in phys. folder to new location using batch mode. As result all original picture was removed to new destination but not one of dependent pictures with different size.
I got tons of messages like:

```
Warning: mkdir(): No such file or directory in /srv/www/piwigo/plugins/physical_photo_move/include/functions.inc.php on line 261

Warning: rename(./_data/i/./galleries/Reisen/1997_Mexiko/Mexico_Flag-2s.png,./_data/i/./galleries/Reisen_bis_2000/1997_Mexico/Mexico_Flag-2s.png): No such file or directory in /srv/www/piwigo/plugins/physical_photo_move/include/functions.inc.php on line 268

Warning: rename(./_data/i/./galleries/Reisen/1997_Mexiko/Mexico_Flag-me.png,./_data/i/./galleries/Reisen_bis_2000/1997_Mexico/Mexico_Flag-me.png): No such file or directory in /srv/www/piwigo/plugins/physical_photo_move/include/functions.inc.php on line 268

Warning: rename(./_data/i/./galleries/Reisen/1997_Mexiko/Mexico_Flag-sm.png,./_data/i/./galleries/Reisen_bis_2000/1997_Mexico/Mexico_Flag-sm.png): No such file or directory in /srv/www/piwigo/plugins/physical_photo_move/include/functions.inc.php on line 268

Warning: rename(./_data/i/./galleries/Reisen/1997_Mexiko/Mexico_Flag-sq.png,./_data/i/./galleries/Reisen_bis_2000/1997_Mexico/Mexico_Flag-sq.png): No such file or directory in /srv/www/piwigo/plugins/physical_photo_move/include/functions.inc.php on line 268
```

All my pictures are in subfolders of: ../galleries/
All dependecies are in subfolders of ../_data/i/galleries/ 

I suppose one reason is a komma after file name (.png,./_data/) and the dot in folder name
 (/_data/i/./galleries)
 
`/Mexico_Flag-sm.png,./_data/i/./galleries`

Nice to get answer an correction.

Holger

**Comment by jradwan** [comment]
Sorry you're having a problem. Hopefully you discovered this in "test mode" and didn't lose anything.

The comma and dot aren't the problem. The comma is separating the two parameters (source and destination) for the rename command. Thus this command:

`rename(./_data/i/./galleries/Reisen/1997_Mexiko/Mexico_Flag-2s.png,./_data/i/./galleries/Reisen_bis_2000/1997_Mexico/Mexico_Flag-2s.png)
`

Is trying to rename:

`./_data/i/./galleries/Reisen/1997_Mexiko/Mexico_Flag-2s.png`

to:

`./_data/i/./galleries/Reisen_bis_2000/1997_Mexico/Mexico_Flag-2s.png`

The single dot won't matter, since it means "current directory" and can be ignored in this context.

So the problem here is probably the first error, from mkdir, which tells me the code failed to create the pwg_representative directory in the new target album's directory (Reisen_bis_2000/1997_Mexico).

Does this happen _anytime_ you use the plugin to move a bunch of photos in batch mode? Or just in this specific album? Can you move the photos one at a time? If you can provide more details maybe I can figure out what's causing the problem.

**Comment by chhoki** [comment]
It was first time move photos this error appears. Since I have to create destination folder manually mkdir fails because of wrong access rights and owner of this new folder
.
Do you have further plans to improve your plugin? 
Maybe move the entire folder from source to destination with all attached data like description,preview photo, access rights and other setups?

Thanks for your reply.

Holger


--
mfg Holger Kirsch

Am Sonntag, Oktober 29, 2017 20:00 CET, Jeremy <notifications@github.com> schrieb:
 
Sorry you're having a problem. Hopefully you discovered this in "test mode" and didn't lose anything.
The comma and dot aren't the problem. The comma is separating the two parameters (source and destination) for the rename command. Thus this command:
rename(./_data/i/./galleries/Reisen/1997_Mexiko/Mexico_Flag-2s.png,./_data/i/./galleries/Reisen_bis_2000/1997_Mexico/Mexico_Flag-2s.png)
Is trying to rename:
./_data/i/./galleries/Reisen/1997_Mexiko/Mexico_Flag-2s.png
to:
./_data/i/./galleries/Reisen_bis_2000/1997_Mexico/Mexico_Flag-2s.png
The single dot won't matter, since it means "current directory" and can be ignored in this context.
So the problem here is probably the first error, from mkdir, which tells me the code failed to create the pwg_representative directory in the new target album's directory (Reisen_bis_2000/1997_Mexico).
Does this happen anytime you use the plugin to move a bunch of photos in batch mode? Or just in this specific album? Can you move the photos one at a time? If you can provide more details maybe I can figure out what's causing the problem.

**Comment by jradwan** [comment]
So you manually created the pwg_representative folder? Not sure why there would be a permission problem. I'll have to see if I can re-create this so I can get some better insight into the root cause.

I do have an enhancement logged (issue #4) to move an entire album at once, but haven't had a lot of time to work on it.

**Comment by jradwan** [comment]
@chhoki I've been poking around a bit starting to work on the "move an entire album at once" feature. I'm still not sure what caused your original problem, but if you can replicate it or get me some more details I'm in a slightly better position now to troubleshoot since I've been re-familiarizing myself with my code. 😉

**Comment by jradwan** [comment]
I haven't heard from you in a while so I'm going to close this. If you run into a similar issue after upgrading to v2.00, please open a new issue.
